# https://docs.travis-ci.com/user/docker/
services:
  - docker

before_install:
  - sudo apt-get update -y
  - sudo apt-get -y install docker-ce

script:
  - docker build -t docker-centos7-ansible .

  # Test running the container.
  - docker run --name test-container -d --privileged -v /sys/fs/cgroup:/sys/fs/cgroup:ro docker-centos7-ansible /usr/lib/systemd/systemd
