# https://docs.travis-ci.com/user/docker/
services:
  - docker

before_install:
- sudo apt-get update -y
- sudo apt-get -y -o Dpkg::Options::="--force-confnew" install docker-ce

script:
# Building the container.
- docker build -t docker-centos7-ansible .

# Test running the container.
- docker run --name test-container -d --privileged -v /sys/fs/cgroup:/sys/fs/cgroup:ro docker-centos7-ansible /usr/lib/systemd/systemd

after_success:
# Pushing the container to docker hub
  - docker login -u "$DOCKERHUB_USERNAME" -p "$DOCKERHUB_PASSWORD"
  - export REPO=$DOCKERHUB_USERNAME/docker-centos7-ansible
  - export TAG=`if [ "$TRAVIS_BRANCH" == "master" ]; then echo "latest"; else echo $TRAVIS_BRANCH ; fi`
  - docker build -t $REPO .
  - docker tag $REPO $REPO:$TAG
  - docker push $REPO
