# https://docs.travis-ci.com/user/docker/
services:
  - docker

env:
  - REPO=$DOCKERHUB_USERNAME/docker-centos7-ansible
  
before_install:
- sudo apt-get update -y
- sudo apt-get -y -o Dpkg::Options::="--force-confnew" install docker-ce

script:
# Building the container.
- docker build -t $REPO .

# Test running the container.
- docker run --name test-container -d --privileged -v /sys/fs/cgroup:/sys/fs/cgroup:ro $REPO /usr/lib/systemd/systemd

after_success:
# Pushing the container to docker hub
  - docker login -u "$DOCKERHUB_USERNAME" -p "$DOCKERHUB_PASSWORD"
  - if [ "$TRAVIS_BRANCH" == "master" ]; then 
    docker tag $REPO $REPO:latest; 
    else 
    docker tag $REPO $REPO:$TRAVIS_BRANCH .; 
    fi
  - if [ -z "$TRAVIS_TAG" ]; then
    echo "TRAVIS_TAG is unset";
    else
    docker build -t $REPO:$TRAVIS_TAG .;
    fi
  - docker images
  - docker push $REPO
